add_executable(game_tests
    conditions/CompositeConditionTests.cpp
    conditions/HealthBelowConditionTests.cpp
    conditions/MinTimeConditionTests.cpp
    conditions/NotConditionTests.cpp
    conditions/VelocityAboveConditionTests.cpp
    AirFrictionSystemTests.cpp
    AnimationLoaderTests.cpp
    AnimationStateSystemTests.cpp
    AnimationSystemTests.cpp
    Camera2DTests.cpp
    CameraControllerSystemTests.cpp
    ComponentRegistryTests.cpp
    CharacterDefinitionLoaderTests.cpp
    CharacterLoaderTests.cpp
    CollisionClipLoaderTests.cpp
    CollisionDetectionSystemTests.cpp
    CollisionHandlerFactoryTests.cpp
    ComboLoaderTests.cpp
    ComboSystemTests.cpp
    ComboTests.cpp
    ConditionFactoryTests.cpp
    DynamicPushboxResolutionSystemTests.cpp
    FrictionSystemTests.cpp
    GameSceneTests.cpp
    GravitySystemTests.cpp
    GroundDetectionSystemTests.cpp
    LocalToWorldSystemTests.cpp
    RenderSystemTests.cpp
    StateMachineLoaderTests.cpp
    StateMapperTests.cpp
    StateSystemTests.cpp
    TextureLoaderTests.cpp
    TriggerBindingLoaderTests.cpp
    TriggerGenerationSystemTests.cpp
    TriggerMapperTests.cpp
    StaticPushboxResolutionSystemTests.cpp
)

target_link_libraries(game_tests
    PRIVATE
        game
        Catch2::Catch2WithMain
)

add_test(NAME game_tests COMMAND game_tests)
